### ISSUE TITLE
Issue with DBal v.3

### ISSUE THREAD

**Issue by ejntaylor** [laravel-shift/factory-generator#10]
Looks like a version clash with latest dbal. Have created a related PR for this:

https://github.com/Naoray/eloquent-model-analyzer/pull/16

Downgrade seems to solve as per:

https://stackoverflow.com/a/64887495/2468603

**Comment by Naoray** [comment]
This was resolved with the [latest release of eloquent-model-analyzer](https://github.com/Naoray/eloquent-model-analyzer/releases/tag/v2.1.2)
