### ISSUE TITLE
Factories in subfolders get the wrong namespace

### ISSUE THREAD

**Issue by mortenscheel** [laravel-shift/factory-generator#18]
Possibly related to #1 

The directory structure of the factories _does_ mirror the models, so if the model is in `app/Feature/Models`, the factory is created in `database/factories/Features/Models`. Which is great.

But the factory namespace is
```php
namespace Database\Factories;
```
And when calling `App\Feature\Models\Foo::factory()`, laravel resolves the factory to `Database\Factories\Feature\Models\FooFactory`, which doesn't exist.

**Comment by jasonmccreary** [comment]
This would be covered by #1. Feel free to open a PR if you have time.
